ID: 2026Y-05M-07D-07h52m35s_RKmO
PID: 1463509
START_DATETIME: 2026-05-07 07:52:35.267001
FILE: /home/ywatanabe/proj/scitex-nn/examples/01_hilbert.py
SDIR_OUT: /home/ywatanabe/proj/scitex-nn/examples/01_hilbert_out
SDIR_RUN: 
    /home/ywatanabe/proj/scitex-nn/examples/01_hilbert_out/RUNNING/2026Y-05M-07D-07h52m35s_RKmO-main
ARGS:
    freq: 10.0
    fs: 512
    t_sec: 1.0
EXIT_STATUS: 0
END_DATETIME: 2026-05-07 07:52:55.808285
RUN_DURATION: 00:00:20
