"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    try:
        audit_all_for_package(
            "scitex-nn",
            skip_rules=("PS108b", "PS121"),  # structural — pending refactor
        )
    except TypeError:
        # scitex-dev <0.11.3 lacks skip_rules — fall back and tolerate
        # the documented structural failures via pytest.xfail.
        pytest.xfail("PS108b/PS121 deferred; needs scitex-dev>=0.11.3 for skip_rules")
